[build]
builder = "nixpacks"
buildCommand = "yarn install && npx expo export -p web"

[deploy]
startCommand = "npx serve dist -s -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
